#!/bin/bash

################################################################################
#                                                                       OS Deps
#
################################################################################
sudo apt-get install \
	autojump \
	curl \
	fzf \
	gawk \
	git \
	jq \
	npm \
	ripgrep \
	taskwarrior \
	tmux \
	vim \
	nvim \
	stow \
	zsh

################################################################################
#                                                                       Chezmoi
#
################################################################################
sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
chezmoi init --apply othondev

################################################################################
#                                                                       TMUX TMP
#
################################################################################
[ -d "$HOME/.tmux/plugins/tpm" ] ||
	git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
