name: CI Pipeline
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: echo "Running a build step"
