name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test dotfiles
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Vim 
        run: |
          sudo apt-get install vim 

      - name: Check Vim Version                                                                                                                                           
        run: |
          vim --version

      - name: Copy Custom Vim Config
        run: |
          cp vim/vimrc ~/.vimrc 

      - name: Test Vim Configuration
        run: |
          vim -c 'qa!'

      - name: Validate Vim Configuration (Lint)
        run: |
          if grep -q 'syntax on' ~/.vimrc; then echo "Syntax highlighting is enabled"; else echo "Syntax highlighting is not enabled"; fi
