name: CI                                                                                                                                                                  

on:
  push:
    branches:
    - '*'

jobs:
  test:
    name: test dotfiles
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Validate .vimrc syntax
        run: |
          sudo apt-get update && sudo apt-get install -y vim 
          vim -Nu vim/vimrc -Es -c "qa"
