name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test dotfiles
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Vim
        run: |
          sudo apt-get update && sudo apt-get install -y vim

      - name: Install Vim and set up .vim directory
        run: |
          mkdir -p ~/.vim/autoload ~/.vim/plugged
          curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

      - name: Copy Custom Vim Config
        run: |
          cp -R vim/ ~/.vim/

      - name: Install and Test Vim Configuration
        run: |
          vim +PlugInstall -c 'qa!'

      - name: Validate Vim Configuration (Lint)
        run: |
          if grep -q 'syntax on' ~/.vimrc; then echo "Syntax highlighting is enabled"; else echo "Syntax highlighting is not enabled"; fi
